version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT= 3000
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_NAME=highscore_mansour

  db:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - highscore_mansour:/data/db
    ports:
      - '27017:27017'

volumes:
  highscore_mansour:
    driver: local
