POST http://localhost:3000/users
Content-Type: application/json

{
"company": "John",
"username": "john@example.com",
"password": "Test",
"address": {
"street": "123 Main St",
"city": "Anytown",
"state": "CA",
"zip": "12345"
}
}

###
POST http://localhost:3000/sessions
Content-Type: application/json

{
"username": "dsdasda@test.at",
"password": "12345678"
}
###
POST http://localhost:3000/highscore
Content-Type: application/json

{
"username": "test@test.at",
"score": "443"
}
###
GET http://localhost:3000/highscore
###
DELETE http://localhost:3000/sessions/312312321
